FROM openjdk:11.0.3-jdk-slim-stretch
ADD ./target/SpringBoot_Restful_Service-0.0.1-SNAPSHOT.jar /app/user/SpringBoot_Restful_Service-0.0.1-SNAPSHOT.jar
WORKDIR app/user
ENTRYPOINT ["java","-jar","SpringBoot_Restful_Service-0.0.1-SNAPSHOT.jar"]



